version: "3.3"
services:
  jdupes:
    build: .
    image: bnowakow/jdupes:0.1-jdupes_1.27.3
    environment:
        UID: 1000
        GUID: 1000
        UMASK: 000
    container_name: jdupes
    entrypoint: jdupes -v

